import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";
import "./studio/Studio.css";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { buildRuntimeProject } from "./generated/buildRuntimeProject";
import type { GeneratedProject } from "./generated/types";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import { Studio } from "./studio/Studio";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const params = new URLSearchParams(window.location.search);
  const projectId = params.get("project");
  const isStudio = window.location.pathname === "/studio";
  const renderStep = params.get("renderStep");
  const renderGlobalStep =
    renderStep == null ? null : Number.parseInt(renderStep, 10);

  if (isStudio) return <Studio />;
  if (projectId)
    return (
      <GeneratedPresentation
        projectId={projectId}
        renderGlobalStep={
          Number.isFinite(renderGlobalStep) ? renderGlobalStep : null
        }
      />
    );

  return <PresentationPlayer chapters={CHAPTERS} audioBasePath="audio" />;
}

function GeneratedPresentation({
  projectId,
  renderGlobalStep,
}: {
  projectId: string;
  renderGlobalStep: number | null;
}) {
  const [project, setProject] = useState<GeneratedProject | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    fetch(`/api/projects/${projectId}`)
      .then(async (res) => {
        const data = await res.json();
        if (!res.ok) throw new Error(data.error || "项目加载失败");
        setProject(data);
      })
      .catch((err) => setError(err instanceof Error ? err.message : String(err)));
  }, [projectId]);

  const runtime = useMemo(
    () => (project ? buildRuntimeProject(project) : null),
    [project],
  );

  if (error) {
    return <div className="app-loading">项目加载失败：{error}</div>;
  }
  if (!runtime) {
    return <div className="app-loading">加载生成项目...</div>;
  }

  return (
      <PresentationPlayer
        chapters={runtime.chapters}
        audioByStep={runtime.audioByStep}
        audioBasePath={runtime.audioBasePath}
        githubUrl={null}
        storageKey={`presentation-cursor-${projectId}`}
      renderGlobalStep={renderGlobalStep}
    />
  );
}

function PresentationPlayer({
  chapters,
  audioByStep,
  audioBasePath,
  githubUrl,
  storageKey,
  renderGlobalStep = null,
}: {
  chapters: typeof CHAPTERS;
  audioByStep?: Record<string, string>;
  audioBasePath: string;
  githubUrl?: string | null;
  storageKey?: string;
  renderGlobalStep?: number | null;
}) {
  const stepper = useStepper(
    chapters,
    renderGlobalStep == null ? storageKey : "presentation-render-cursor",
    renderGlobalStep,
  );
  const activeChapter = chapters[stepper.cursor.chapter]!;
  const Cmp = activeChapter.Component;
  const stepText = activeChapter.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioFile =
    audioByStep?.[`${activeChapter.id}:${stepper.cursor.step + 1}`] ||
    `${activeChapter.id}/${stepper.cursor.step + 1}.mp3`;
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}${audioBasePath}/${audioFile}`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={activeChapter.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      {renderGlobalStep == null && (
        <>
          <ProgressBar
            chapters={chapters}
            cursor={stepper.cursor}
            onJumpChapter={stepper.jumpToChapter}
            githubUrl={githubUrl}
          />
          <AutoToggle mode={mode} onCycle={cycleMode} />
          <AutoStartGate
            visible={mode === "auto" && !autoStarted}
            onStart={() => setAutoStarted(true)}
          />
        </>
      )}
    </>
  );
}
